### ISSUE TITLE
Custom Reference Altas  

### ISSUE THREAD

**Issue by TadhgCy** [carmonalab/ProjecTILs#3]
Thanks for creating such a powerful tool, I have been projecting my own human and mouse data onto the supplied reference atlas and found it to be a great addition to my standard workflow. 

However, I have been having some trouble generating my own reference atlas. I think this is due to a lot of objects in ref.atlas@misc. 

If you could share the code that was used to generate the structure of the atlas it would help me out, thanks!

**Comment by mass-a** [comment]
Hello and thanks for the comment!
You are right that it is not trivial to generate a reference atlas with the correct structure.

We are currently preparing a vignette documenting the generation of a custom reference atlas. We'll keep you posted here when it's ready!

**Comment by mass-a** [comment]
We have now added a short tutorial for the preparation of a Seurat object to be used as a custom reference atlas:

- [https://carmonalab.github.io/ProjecTILs/build_ref_atlas.html](https://carmonalab.github.io/ProjecTILs/build_ref_atlas.html)

I hope you can adapt this code to your own atlas. Otherwise feel free to get in touch!
