### ISSUE TITLE
How to turn the result into a human homologous gene?

### ISSUE THREAD

**Issue by ESUIT-SU** [carmonalab/ProjecTILs#35]
Hello, we all know that the result is a mouse gene, how to turn the result into a human homologous gene?

**Comment by mass-a** [comment]
Hello, I'm not sure I understand the question, but if you look to translate orthologs between mouse and human you can use the conversion table distributed with ProjecTILs named `ProjecTILs::Hs2Mm.convert.table`.
```
head(ProjecTILs::Hs2Mm.convert.table)
```
```
  Gene.stable.ID.HS Gene.HS Gene.MM Alt.symbol Alt.symbol.HS
1   ENSG00000198888  MT-ND1  mt-Nd1     mt-Nd1        MT-ND1
2   ENSG00000198763  MT-ND2  mt-Nd2     mt-Nd2        MT-ND2
3   ENSG00000198804  MT-CO1  mt-Co1     mt-Co1        MT-CO1
4   ENSG00000198712  MT-CO2  mt-Co2     mt-Co2        MT-CO2
5   ENSG00000228253 MT-ATP8 mt-Atp8    mt-Atp8       MT-ATP8
6   ENSG00000198899 MT-ATP6 mt-Atp6    mt-Atp6       MT-ATP6
```

**Comment by ESUIT-SU** [comment]
Thank you for your thoughtful answer. Because we felt that your study clearly identified T cell subsets, we wanted to use ProjecTILs to analyze single-cell sequencing data from human tumors. But ProjecTILs convert human genes into homologous mouse genes, and we can't do the next analysis because we need to use human genes. I also tried the `ProjecTILs::Hs2Mm.convert.table` you mentioned before. But I found that some genes in my `rownames(obj)` result are not in the Hs2Mm.convert.table you provided, such as 2700097O09Rik
, Gm46350, Gm7511 and so on. Why is this?

**Comment by mass-a** [comment]
Hello again,
you are correct, it's possible that some genes of the reference have been included in the projected object, to enable query-reference comparison. You should be able to safely ignore these genes (i.e. remove them from the data matrix) if you convert back to human orthologs.

Another possibility, in case you are only interested in the cell type labels assigned by the method, would be to map the "functional cluster" column of the annotated object back to your original data. The barcodes are the same so that should be straightforward. Does this make sense?

Best
-m
