### ISSUE TITLE
How to use Run.Projectils for a merged dataset with SCT assay

### ISSUE THREAD

**Issue by mckoch234** [carmonalab/ProjecTILs#62]
Hello, I am trying to run run.projectiles with the sct assay however I am getting this error Error: SCT assay is comprised of multiple SCT models. To change the variable features, please set manually with VariableFeatures<- . I did set it manually with variable featuers however it is still giving me the same error.

**Comment by mass-a** [comment]
Hello! can you tell us if you are using objects in Seurat v5 format? it would be great if you could provide a piece of code and your `SessionInfo()`, so that we can try to reproduce your error. In general, regardless of how you merged/integrated your dataset, I would recommend to provide uncorrected data ('RNA assay') to ProjecTILs, possibly split by sample (see [this case study](https://carmonalab.github.io/ProjecTILs_CaseStudies/Bassez_BC.html) for an example.

-m

**Comment by alicekao1118** [comment]
@mckoch234 could you share how you fix this issue? I got the same error. But Seurat v5 can't `JoinLayers() `with SCT assays.

**Comment by mckoch234** [comment]
I used PrepSCTFindmarkers().
